[build]
  publish = "Static/dist"
  command = "make build"

[build.environment]
  NODE_VERSION = "18"
  SWIFT_VERSION = "6.2"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[dev]
  command = "make dev"
  port = 3000
  publish = "Static/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
