name: deploy

on:
  push:
    branches:
      - main
jobs:
  blog-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Blog Generate
        run: make run
        
      - name: Run Tailwind CSS
        run: make tailwind
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./Output
          publish_branch: master
