name: deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  blog-deploy:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Generate blog
        run: make run
        
      - name: Run Tailwind CSS
        run: make tailwind
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./Output
          publish_branch: master
