name: deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  blog-deploy:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 15
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app
      
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Generate blog
        run: make run
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Tailwind CSS
        run: make tailwind
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./Output
          publish_branch: gh-pages
          cname: blog.jihoon.me

  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get the content of config file
        id: algolia_config
        run: echo "config=$(cat docsearch.config.json | jq -r tostring)" >> $GITHUB_OUTPUT

      - name: Push indices to Algolia
        uses: signcl/docsearch-scraper-action@master
        env: 
            APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
            API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
            CONFIG: ${{ steps.algolia_config.outputs.config }}